### PR TITLE
Add svg icons

### PR DESCRIPTION
**Pull request by Suzie97**
This PR adds svg versions for the current png icon for better clarity and readability.

### CODE REVIEW

**Comment by ryonakano** [comment]
Hi, thank you for your PR! Really nice work, excellent! 🥳🎉

Just two things I'd like you to do & I want to confirm:

- would you remove the `.DS_Store` files maybe added by your macOS?
- did you use [the elementary color palette](https://elementary.io/brand) for icon colors?

**Comment by Suzie97** [comment]
> Hi, thank you for your PR! Really nice work, excellent! 🥳🎉
> 
> Just two things I'd like you to do & I want to confirm:
> 
> * would you remove the `.DS_Store` files maybe added by your macOS?
> * did you use [the elementary color palette](https://elementary.io/brand) for icon colors?

Sorry about the `.DS_Store` files, I'll remove them.

And yes, I used the elementary palette colours for the icon.

**Comment by Suzie97** [comment]
@ryonakano I made the requested changes :))

**Review by ryonakano — APPROVED** [review]
Really appreciate your work, thank you! :heart:

**Pull request merged**
